
version: 0.2
phases:
  install:
    run-as: root
    runtime-versions:
      nodejs: 14
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - npm install -g @ionic/cli
  pre_build:
    commands:
      - export AWS_ACCOUNT_id="928624967233"
      - export REPO_URL="${AWS_ACCOUNT_id}.dkr.ecr.us-east-2.amazonaws.com"
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${REPO_URL}
      - export IMAGE="${REPO_URL}/best-ride-ui:1.0"
  build:
    commands:
      - npm install
      - ionic build --prod
      - docker build -t ${IMAGE} .
      - docker push ${IMAGE}
  post_build:
    commands:
      - printf '[{"name":"best-ride-ui", "imageUri":"%s"}]' ${IMAGE} > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json

